### ISSUE TITLE
Public API

### ISSUE THREAD

**Issue by cofob** [mitsuhiko/teetty#4]
Hi, I would like to integrate this project into my program. Could you make `lib.rs` file with public API and publish on crates.io?

**Comment by mitsuhiko** [comment]
That's sort of my plan once I figure out the details of what this could look like. The use of `fork()` makes this quite tricky to wrap safely. Additionally it does not have windows support yet which might have an impact on the API of this thing.

**Comment by mitsuhiko** [comment]
This will land in the next release.
